plugins {
    id 'dev.architectury.loom-no-remap' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    noIntermediateMappings()
}

repositories {
    maven { url "https://maven.shedaniel.me" }
    maven { url "https://maven.architectury.dev" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation "me.shedaniel:RoughlyEnoughItems-fabric:${project.rei_version}"
    implementation "me.shedaniel.cloth:basic-math:0.6.1"
    compileOnly "me.shedaniel.cloth:cloth-config-fabric:26.2.155"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}
